# Generated by Django 2.1.3 on 2020-09-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'short'), ('gown', 'gown'), ('bonnet', 'bonnet')], max_length=30, null=True),
        ),
    ]
