# Generated by Django 2.1.3 on 2020-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200905_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='apartmentaddress',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='streetaddress',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='town',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'short'), ('gown', 'gown'), ('bonnet', 'bonnet')], max_length=30, null=True),
        ),
    ]
