# Generated by Django 2.1.3 on 2020-09-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200905_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bonnet', 'bonnet'), ('short', 'short'), ('gown', 'gown')], max_length=30, null=True),
        ),
    ]
