# Generated by Django 2.1.3 on 2020-09-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200905_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'short'), ('bonnet', 'bonnet'), ('gown', 'gown')], max_length=30, null=True),
        ),
    ]
