# Generated by Django 2.1.3 on 2020-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'short'), ('bonnet', 'bonnet'), ('gown', 'gown')], max_length=30),
        ),
    ]
