# Generated by Django 2.1.3 on 2020-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201013_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bonnet', 'bonnet'), ('gown', 'gown'), ('short', 'short')], max_length=30),
        ),
    ]
