# Generated by Django 2.1.3 on 2020-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20201013_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('short', 'short'), ('bonnet', 'bonnet'), ('gown', 'gown')], max_length=30),
        ),
    ]
