# Generated by Django 2.1.3 on 2020-08-06 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200805_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 20, 30, 11, 996140)),
        ),
    ]
