# Generated by Django 2.1.3 on 2020-08-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200807_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 8, 15, 6, 45, 910411)),
        ),
    ]
