# Generated by Django 2.1.3 on 2020-08-31 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200831_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 22, 13, 56, 247610)),
        ),
    ]
