# Generated by Django 2.1.3 on 2020-08-31 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20200831_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 23, 52, 30, 941160)),
        ),
    ]
