# Generated by Django 2.1.3 on 2020-09-01 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_auto_20200831_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 0, 40, 32, 774036)),
        ),
    ]
