# Generated by Django 2.1.3 on 2020-09-02 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20200902_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 2, 12, 25, 720505)),
        ),
    ]
