# Generated by Django 2.1.3 on 2020-09-05 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20200902_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 5, 15, 22, 2, 805726)),
        ),
    ]
