# Generated by Django 2.1.3 on 2020-09-05 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20200905_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 5, 21, 6, 22, 731908)),
        ),
    ]
