# Generated by Django 2.1.3 on 2020-09-06 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20200905_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 6, 17, 42, 29, 97498)),
        ),
    ]
